export default {
    questions: [],
    currentIndex: 0,
    currentTitle: "Select a question",
    currentOptions: [],
    userAnswers: {},
    confirmedAnswers: {},
    totalSeconds: 0,
    timeUp: false,
    timer: null,
    progress: 0,
    showPopup: false,
    showHelp: false,
    showContact: false,
    showCalculator: false,
    calcInput: "",
    calcButtons: [
        "7",
        "8",
        "9",
        "/",
        "4",
        "5",
        "6",
        "*",
        "1",
        "2",
        "3",
        "-",
        "0",
        "C",
        "+",
        "=",
    ],
    strikethroughAnswers: {},
    showEndTestModal: false,
    isDarkMode: false,
    resultLoaded: false,
    finalResult: {},
    showFilterPopup: false,
    filter: {
      selected: "" // values: 'answered', 'unanswered', 'flagged'
    },
    
};
